/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ProjetoCSS.view;

import br.com.ProjetoCSS.controller.UsuarioDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.util.*;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Beatriz
 */
public class JFUsuario extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    UsuarioDAO usuariodao = new UsuarioDAO();
    int flag;

    /**
     * Creates new form JFCliente
     */
    public JFUsuario() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        edtId = new javax.swing.JTextField();
        edtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edtLogin = new javax.swing.JTextField();
        CB_Perfil = new javax.swing.JComboBox<>();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        radID = new javax.swing.JRadioButton();
        RadNome = new javax.swing.JRadioButton();
        edtPesquisa = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUsuario = new javax.swing.JTable();
        edtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        edtSenha = new javax.swing.JPasswordField();
        edtSenhaE = new javax.swing.JPasswordField();
        edtEnd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        edtCpf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        edtRg = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        edtTelDDD = new javax.swing.JFormattedTextField();
        edtTelId = new javax.swing.JFormattedTextField();
        edtTelNum = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Usuarios");
        setAutoRequestFocus(false);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Confirmar Senha");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, -1, -1));

        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel3.setText("Nome");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        edtId.setEnabled(false);
        edtId.setFocusable(false);
        getContentPane().add(edtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 40, -1));
        getContentPane().add(edtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 371, -1));

        jLabel4.setText("Login");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, -1, -1));

        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));
        getContentPane().add(edtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 180, -1));

        CB_Perfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione sua Opção", "Usuário", "Administrador" }));
        getContentPane().add(CB_Perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 180, -1));

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });
        getContentPane().add(btnInserir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));

        buttonGroup1.add(radID);
        radID.setText("ID");
        radID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radIDActionPerformed(evt);
            }
        });
        getContentPane().add(radID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        buttonGroup1.add(RadNome);
        RadNome.setText("Nome");
        RadNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadNomeActionPerformed(evt);
            }
        });
        getContentPane().add(RadNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        edtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtPesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(edtPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 190, -1));

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, -1, -1));

        tbUsuario.setBackground(new java.awt.Color(0, 206, 209));
        tbUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Login", "Perfil"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbUsuario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 700, 170));
        getContentPane().add(edtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 371, -1));

        jLabel6.setText("Senha");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, -1, 20));
        getContentPane().add(edtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 180, -1));
        getContentPane().add(edtSenhaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 180, -1));

        edtEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtEndActionPerformed(evt);
            }
        });
        getContentPane().add(edtEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 371, -1));

        jLabel7.setText("Endereço");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        jLabel8.setText("CPF");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        edtCpf.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                edtCpfPropertyChange(evt);
            }
        });
        edtCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtCpfKeyTyped(evt);
            }
        });
        getContentPane().add(edtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 100, -1));

        jLabel9.setText("RG");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        edtRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtRgActionPerformed(evt);
            }
        });
        edtRg.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                edtRgPropertyChange(evt);
            }
        });
        edtRg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtRgKeyTyped(evt);
            }
        });
        getContentPane().add(edtRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 80, -1));

        jLabel10.setText("Telefone");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("-");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 170, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("(");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText(")");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        jLabel14.setText("Tipo");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 760, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Cadastrar");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Consultar");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        edtTelDDD.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        edtTelDDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtTelDDDActionPerformed(evt);
            }
        });
        edtTelDDD.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                edtTelDDDPropertyChange(evt);
            }
        });
        edtTelDDD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtTelDDDKeyTyped(evt);
            }
        });
        getContentPane().add(edtTelDDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 170, 30, -1));

        edtTelId.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                edtTelIdPropertyChange(evt);
            }
        });
        edtTelId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtTelIdKeyTyped(evt);
            }
        });
        getContentPane().add(edtTelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 50, -1));

        edtTelNum.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                edtTelNumPropertyChange(evt);
            }
        });
        edtTelNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtTelNumKeyTyped(evt);
            }
        });
        getContentPane().add(edtTelNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 170, 50, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void StatusBotao(int btnAtivo) {

        if (btnAtivo == 0) {

            edtNome.setEnabled(true);
            edtLogin.setEnabled(true);
            edtSenha.setEnabled(true);
            edtSenhaE.setEnabled(true);
            edtTelDDD.setEnabled(true);
            edtTelId.setEnabled(true);
            edtTelNum.setEnabled(true);
            edtCpf.setEnabled(true);
            edtRg.setEnabled(true);
            edtEnd.setEnabled(true);
            edtEmail.setEnabled(true);
            CB_Perfil.setEnabled(true);
            edtPesquisa.setEnabled(false);
            buttonGroup1.clearSelection();

            edtId.setText("");
            edtNome.setText("");
            edtLogin.setText("");
            edtSenha.setText("");
            edtSenhaE.setText("");
            edtTelDDD.setText("");
            edtTelId.setText("");
            edtTelNum.setText("");
            edtCpf.setText("");
            edtRg.setText("");
            edtEnd.setText("");
            edtEmail.setText("");
            CB_Perfil.setSelectedIndex(0);
            edtPesquisa.setText("");
            
            

            btnAlterar.setEnabled(false);
            btnSalvar.setEnabled(true);
            btnDeletar.setEnabled(false);
            btnCancelar.setEnabled(true);
            btnInserir.setEnabled(false);

        }

        if (btnAtivo == 1) {
//            edtNome.setEnabled(false);
//            edtLogin.setEnabled(false);
//            edtSenha.setEnabled(false);
//            edtSenhaE.setEnabled(false);
//            edtTelDDD.setEnabled(false);
//            edtTelId.setEnabled(false);
//            edtTelNum.setEnabled(false);
//            edtCpf.setEnabled(false);
//            edtRg.setEnabled(false);
//            edtEnd.setEnabled(false);
//            edtEmail.setEnabled(false);
//            CB_Perfil.setEnabled(false);
//            CB_Perfil.setSelectedIndex(0);
//            edtPesquisa.setEnabled(false);
//            edtPesquisa.setText("");
//            buttonGroup1.clearSelection();
//
//            btnAlterar.setEnabled(true);
//            btnSalvar.setEnabled(false);
//            btnDeletar.setEnabled(true);
//            btnCancelar.setEnabled(false);
//            btnInserir.setEnabled(true);

            edtNome.setEnabled(false);
            edtLogin.setEnabled(false);
            edtSenha.setEnabled(false);
            edtSenhaE.setEnabled(false);
            edtTelDDD.setEnabled(false);
            edtTelId.setEnabled(false);
            edtTelNum.setEnabled(false);
            edtCpf.setEnabled(false);
            edtRg.setEnabled(false);
            edtEnd.setEnabled(false);
            edtEmail.setEnabled(false);
            CB_Perfil.setEnabled(false);
            CB_Perfil.setSelectedIndex(0);
            edtPesquisa.setEnabled(false);
            edtPesquisa.setText("");
            buttonGroup1.clearSelection();

            btnAlterar.setEnabled(false);
            btnSalvar.setEnabled(false);
            btnDeletar.setEnabled(false);
            btnCancelar.setEnabled(false);
            btnInserir.setEnabled(true);
            // atualizaID();

        }

        if (btnAtivo == 2) {

            edtNome.setEnabled(true);
            edtLogin.setEnabled(true);
            edtSenha.setEnabled(true);
            edtSenhaE.setEnabled(true);
            edtTelDDD.setEnabled(true);
            edtTelId.setEnabled(true);
            edtTelNum.setEnabled(true);
            edtCpf.setEnabled(true);
            edtRg.setEnabled(true);
            edtEnd.setEnabled(true);
            edtEmail.setEnabled(true);
            CB_Perfil.setEnabled(true);
            CB_Perfil.setSelectedIndex(0);
            buttonGroup1.clearSelection();
            edtPesquisa.setEnabled(false);
            edtPesquisa.setText("");

            btnInserir.setEnabled(false);
            btnSalvar.setEnabled(true);
            btnDeletar.setEnabled(false);
            btnCancelar.setEnabled(true);

        }
        
        if(btnAtivo == 3){
            edtNome.setEnabled(false);
            edtLogin.setEnabled(false);
            edtSenha.setEnabled(false);
            edtSenhaE.setEnabled(false);
            edtTelDDD.setEnabled(false);
            edtTelId.setEnabled(false);
            edtTelNum.setEnabled(false);
            edtCpf.setEnabled(false);
            edtRg.setEnabled(false);
            edtEnd.setEnabled(false);
            edtEmail.setEnabled(false);
            CB_Perfil.setEnabled(false);
            CB_Perfil.setSelectedIndex(0);
            edtPesquisa.setEnabled(false);
            edtPesquisa.setText("");
            buttonGroup1.clearSelection();

            btnAlterar.setEnabled(true);
            btnSalvar.setEnabled(false);
            btnDeletar.setEnabled(true);
            btnCancelar.setEnabled(false);
            btnInserir.setEnabled(true);
        }
        
        
        if (btnAtivo == 4) {

            edtPesquisa.setEnabled(false);
            buttonGroup1.clearSelection();

            edtId.setText("");
            edtNome.setText("");
            edtLogin.setText("");
            edtSenha.setText("");
            edtSenhaE.setText("");
            edtTelDDD.setText("");
            edtTelId.setText("");
            edtTelNum.setText("");
            edtCpf.setText("");
            edtRg.setText("");
            edtEnd.setText("");
            edtEmail.setText("");
            CB_Perfil.setSelectedIndex(0);
            edtPesquisa.setText("");
            
            

            btnAlterar.setEnabled(false);
            btnSalvar.setEnabled(false);
            btnDeletar.setEnabled(false);
            btnCancelar.setEnabled(false);
            btnInserir.setEnabled(true);
    }
    }
    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        // TODO add your handling code here:
        StatusBotao(0);
        flag = 0;
        Logger log;

    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        flag = 1;
        StatusBotao(2);

    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        usuariodao.DeletaUsu(Integer.parseInt(edtId.getText()));
       StatusBotao(4);
        try {
            tbUsuario.setModel(fill(usuariodao.ConsultarAll()));
        } catch (SQLException ex) {
            Logger.getLogger(JFUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        String telefone = edtTelDDD.getText() + edtTelId.getText() + edtTelNum.getText();
        boolean usuTipo = (CB_Perfil.getSelectedIndex() - 2) != 0;

        if (edtNome.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Insira um Nome para o Usuário");
            return;
        }
        if (edtLogin.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Insira um Login para o Usuário");
            return;
        }
        if (edtSenha.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Insira a Senha para o Usuário");
            return;
        }
        if (!(edtSenha.getText().equals(edtSenhaE.getText()))) {
            JOptionPane.showMessageDialog(this, "Confirme a Senha");
            return;
        }
        if (CB_Perfil.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Selecione um Tipo para Usuário");
            return;
        }
        if (telefone.length() != 11 && telefone.length() != 0){
            JOptionPane.showMessageDialog(this, "Coloque um telefone válido ((DDD) XXXXX-XXXX)");
            return;
        }

        if (flag == 0) {

            if (edtSenha.getText().equals(edtSenha.getText())) {                
                try{
                usuariodao.InsereUsu(edtNome.getText(), edtEnd.getText(), Long.parseLong(edtCpf.getText()), Integer.parseInt(edtRg.getText()), Long.parseLong(telefone), edtLogin.getText(), edtEmail.getText(), edtSenha.getText(), usuTipo);
                } catch (NumberFormatException ex){
                    JOptionPane.showMessageDialog(null, "Telefone vazio/inválido - O cadastro será efetuado sem telefone");
                    usuariodao.InsereUsu(edtNome.getText(), edtEnd.getText(), Long.parseLong(edtCpf.getText()), Integer.parseInt(edtRg.getText()), Long.parseLong("0"), edtLogin.getText(), edtEmail.getText(), edtSenha.getText(), usuTipo);
                }
                StatusBotao(0);
                StatusBotao(1);

//                // atualizaID();
            } else {
                JOptionPane.showMessageDialog(this, "As senhas não conferem. Digite novamente");
                edtSenha.setText(null);
                edtSenha.setText(null);
                edtSenha.requestFocus();
            }

        } else if (flag == 1 && edtSenha.getText().equals(edtSenha.getText())) {
            usuariodao.AlterarUsu(Integer.parseInt(edtId.getText()), edtNome.getText(), edtEnd.getText(), Long.parseLong(edtCpf.getText()), Integer.parseInt(edtRg.getText()), Long.parseLong(telefone), edtLogin.getText(), edtEmail.getText(), edtSenha.getText(), usuTipo);
        } else {
            JOptionPane.showMessageDialog(this, "As senhas não conferem. Digite novamente");
            edtSenha.setText(null);
            edtSenha.setText(null);
            edtSenha.requestFocus();
        }
        try {
            tbUsuario.setModel(fill(usuariodao.ConsultarAll()));
        } catch (SQLException ex) {
            Logger.getLogger(JFUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        StatusBotao(1);
        edtId.setText("");
        edtNome.setText("");
        edtLogin.setText("");
        edtSenha.setText("");
        edtSenhaE.setText("");
        edtCpf.setText("");
        edtEmail.setText("");
        edtEnd.setText("");
        edtTelDDD.setText("");
        edtTelNum.setText("");
        edtTelId.setText("");
        edtRg.setText("");
        

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void edtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtPesquisaActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed

        if (radID.isSelected()) {

            try {
                tbUsuario.setModel(fill(usuariodao.ConsultarID(Integer.parseInt(edtPesquisa.getText()))));
            } catch (SQLException ex) {
                Logger.getLogger(JFUsuario.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NumberFormatException nex) {
                JOptionPane.showMessageDialog(null, "Número inválido");
            }

            if (tbUsuario.getRowCount() == 0) {

                JOptionPane.showMessageDialog(this, "Registro não encontrado");
            }
        }

        if (RadNome.isSelected()) {

            try {
                tbUsuario.setModel(fill(usuariodao.ConsultarNome(edtPesquisa.getText())));
            } catch (SQLException ex) {
                Logger.getLogger(JFUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }

            if (tbUsuario.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Registro não encontrado");
            }
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void tbUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUsuarioMouseClicked
        // TODO add your handling code here:
        if (tbUsuario.getSelectedRow() != -1) {
            editMode();
            StatusBotao(3);
        }
    }//GEN-LAST:event_tbUsuarioMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        StatusBotao(1);
        try {
            tbUsuario.setModel(fill(usuariodao.ConsultarAll()));
        } catch (SQLException ex) {
            Logger.getLogger(JFUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void edtEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtEndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtEndActionPerformed

    private void edtRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtRgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtRgActionPerformed

    private void edtTelDDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtTelDDDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtTelDDDActionPerformed

    private void edtTelDDDPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_edtTelDDDPropertyChange
        
    }//GEN-LAST:event_edtTelDDDPropertyChange

    private void edtTelIdPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_edtTelIdPropertyChange
        
    }//GEN-LAST:event_edtTelIdPropertyChange

    private void edtTelNumPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_edtTelNumPropertyChange
        
    }//GEN-LAST:event_edtTelNumPropertyChange

    private void edtCpfPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_edtCpfPropertyChange
        
    }//GEN-LAST:event_edtCpfPropertyChange

    private void edtRgPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_edtRgPropertyChange
        
    }//GEN-LAST:event_edtRgPropertyChange

    private void edtCpfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCpfKeyTyped
        setSizeLimit(edtCpf, 11);
    }//GEN-LAST:event_edtCpfKeyTyped

    private void edtRgKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtRgKeyTyped
        setSizeLimit(edtRg, 9);
    }//GEN-LAST:event_edtRgKeyTyped

    private void edtTelDDDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtTelDDDKeyTyped
        setSizeLimit(edtTelDDD, 2);
    }//GEN-LAST:event_edtTelDDDKeyTyped

    private void edtTelIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtTelIdKeyTyped
        setSizeLimit(edtTelId, 5);
    }//GEN-LAST:event_edtTelIdKeyTyped

    private void edtTelNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtTelNumKeyTyped
        setSizeLimit(edtTelNum, 4);
    }//GEN-LAST:event_edtTelNumKeyTyped

    private void radIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radIDActionPerformed
        edtPesquisa.setEnabled(true);
    }//GEN-LAST:event_radIDActionPerformed

    private void RadNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadNomeActionPerformed
        edtPesquisa.setEnabled(true);
    }//GEN-LAST:event_RadNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JFUsuario().setVisible(true);
        });
    }

    public static DefaultTableModel fill(ResultSet rs) throws SQLException {
        ResultSetMetaData metaData = rs.getMetaData();
        int count = metaData.getColumnCount();

        Vector<String> names = new Vector<>();
        for (int i = 1; i <= count; i++) {
            names.add(metaData.getColumnName(i));
        }

        Vector<Vector<Object>> data = new Vector<>();
        while (rs.next()) {
            Vector<Object> vector = new Vector<>();
            for (int i = 1; i <= count; i++) {
                vector.add(rs.getObject(i));
            }
            data.add(vector);
        }

        return new DefaultTableModel(data, names);
    }

    public void editMode() {
        String telefone = tbUsuario.getValueAt(tbUsuario.getSelectedRow(),5).toString();
                
        btnAlterar.setEnabled(true);
        btnDeletar.setEnabled(true);
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        edtId.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 0).toString());
        edtNome.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 1).toString());
        edtEnd.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 2).toString());
        edtCpf.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(),3).toString());
        edtRg.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(),4).toString());
        edtTelNum.setText(telefone.substring(7,11));
        edtTelDDD.setText(telefone.substring(0,2));
        edtTelId.setText(telefone.substring(2,7));
        edtEmail.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(),7).toString());
        edtLogin.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 8).toString());                    
        CB_Perfil.setSelectedIndex(tbUsuario.getValueAt(tbUsuario.getSelectedRow(),10).toString().equals("true") ? 2 : 1 );

    }
    
    public void setSizeLimit(JTextField tf, int size){
        String subs;
        if(tf.getText().length() == size){
            subs = tf.getText().substring(0, size - 1);
            tf.setText(subs);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_Perfil;
    private javax.swing.JRadioButton RadNome;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField edtCpf;
    private javax.swing.JTextField edtEmail;
    private javax.swing.JTextField edtEnd;
    private javax.swing.JTextField edtId;
    private javax.swing.JTextField edtLogin;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtPesquisa;
    private javax.swing.JTextField edtRg;
    private javax.swing.JPasswordField edtSenha;
    private javax.swing.JPasswordField edtSenhaE;
    private javax.swing.JFormattedTextField edtTelDDD;
    private javax.swing.JFormattedTextField edtTelId;
    private javax.swing.JFormattedTextField edtTelNum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton radID;
    private javax.swing.JTable tbUsuario;
    // End of variables declaration//GEN-END:variables
}
